packages: []

catalogs:
  build:
    '@iconify-json/carbon': ^1.2.11
    '@vitejs/plugin-vue': ^5.2.4
    jsdom: ^26.1.0
    unocss: ^66.3.3
    unplugin: ^2.3.5
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.8.0
    unplugin-vue-macros: ^2.14.5
    vite: ^6.3.5
    vite-plugin-wasm: ^3.5.0
  dev:
    '@antfu/eslint-config': ^4.19.0
    '@types/node': ^22.17.0
    '@unocss/eslint-plugin': ^66.3.3
    '@vue-macros/volar': 3.0.0-beta.20
    '@vue/test-utils': ^2.4.6
    eslint: ^9.32.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.1
    taze: ^19.1.0
    typescript: ^5.9.2
    vitest: ^3.2.4
    vue-tsc: ^2.2.12
  frontend:
    '@dimforge/rapier2d': ^0.18.0
    '@vueuse/core': ^13.6.0
    lz-string: ^1.5.0
    vue: ^3.5.18

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
